# Page settings
baseurl = "https://cometothetable-40968.firebaseapp.com"
title = "Come to the Table, Inc."
languageCode = "en-us"
theme = "hugo-elate-theme"
publishdir = "../come2thetable.org"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Come to the Table, Inc."
  description = "Website for Come to the Table, Inc."
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "Come to the Table, Inc."
    home = "Home"
    work = "Donate"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Providing dignified meals to people in need."
    subtitle = 'We strive to build connections and communicate compassion through food, serving meals that we would proudly serve to our own friends and family.'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Donate"
    description = "We survive on small regular donations -- and you can make a difference. Join our donor club by giving $3/month!"
    footertext = ''

    [[params.work.row]]
      img = "IMG_1491.jpg"
      alt = "Dayne pulling BBQ off the smoker"
      title = ""
      subtitle = ""

    [[params.work.row]]
      img = "IMG_1495.jpg"
      alt = "Kim and Rose"
      title = ""
      subtitle = ""

    [[params.work.row]]
      img = "IMG_1498.jpg"
      alt = "Dave next to the smoker"
      title = ""
      subtitle = ""

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = false
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Come to the Table, Inc. was born out an observed disconnect between the people serving and those receiving. All too often, those serving would not readily eat the very food they handed to others. We would never discourage help to people in need, but we believe the food we serve conveys a message of worth. We strive to show dignity and communicate worth by serving food we would happily share with our own families and loved ones. Come and join us at our table."

    [[params.about.item]]
      name = "Dayne Filer"
      position = "Co-founder, Director"
      description = "Dayne is a medical student at UNC-Chapel Hill and an enthusiastic home cook. He very much enjoys cooking for a crowd, and feels priviledged to serve through Come to the Table, Inc."
      img = "Dayne.jpg"
      alt = "Dayne L Filer"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/daynefiler/"],
        ["icon-envelope", "mailto:dayne@come2thetable.org"],
        ["icon-dribbble", "https://daynefiler.github.io"]
      ]

    [[params.about.item]]
      name = "Dave Lyons"
      position = "Founder, Board Member"
      description = ""
      img = "Dave.jpg"
      alt = "Dave M Lyons"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/lyonsd/"],
        ["icon-envelope", "mailto:dave@come2thetable.org"]
      ]

      [[params.about.item]]
        name = "Kim Lyons"
        position = "Co-founder, Board Member"
        description = ""
        img = "Kim.jpg"
        alt = "Kim Lyons"
        social = [
          ["icon-linkedin", "https://www.linkedin.com/in/kim-lyons-9844b24"],
          ["icon-envelope", "mailto:kim@come2thetable.org"]
        ]



    [[params.about.item]]
      name = "Samuel Fleder"
      position = "Attorney"
      description = "Sam and his firm, Smith Debnam, generously provide pro bono legal counsel for Come to the Table, Inc." # <br> <br> <img ali src=\"/images/smithdebnam.gif\" class = \"center90\">"
      img = "Sam.jpg"
      alt = "Samuel Fleder, JD"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/samuel-fleder-99571317"],
        ["icon-envelope", "mailto:sfleder@smithdebnamlaw.com"],
        ["icon-dribbble", "https://www.smithdebnamlaw.com/people/samuel-d-fleder/"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "IMG_1487.JPG"

    [[params.counters.item]]
      description = "Months in operation"
      icon = "icon-calendar"
      from = 0
      to = 16
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Pounds of chicken and pork"
      icon = "icon-basket-loaded"
      from = 0
      to = 2560
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Meals served"
      icon = "icon-people"
      from = 0
      to = 2320
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Hours prepping and cooking food"
      icon = "icon-hourglass"
      from = 0
      to = 256
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = false
    title = "Get in touch"
    description = "We would love to hear from you. <br> <a href=\"mailto:info@come2thetable.org\">Send us a line.</a>"

    # Available icons: http://simplelineicons.com/
    details = [
        #["icon-home", "Durham, NC"],
        #["icon-phone", "(123) 465-6789"],
        #["icon-envelope", "dayne.filer@gmail.com"]#,
        #["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Come to the Table, Inc. All Rights Reserved. <br> We are a 501(c)(3) organization, EIN: #00-000000; <a href="http://come2thetable.org/CTTT-IRS-letter.pdf" target="_blank">IRS Letter</a> <br> We are indebted to <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> and <a href="https://github.com/saey55" target="_blank">saey55</a> for their website template.'
    #links = [
    #    ["icon-twitter", "#twitter"],
    #    ["icon-facebook", "#facebook"],
    #    ["icon-youtube", "#youtube"]
    #  ]
